/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiMachineServiceConcurrency struct {
	HardLimit int32 `json:"hard_limit,omitempty"`
	SoftLimit int32 `json:"soft_limit,omitempty"`
	Type_ string `json:"type,omitempty"`
}
