/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponse struct {
	// Deprecated
	Details *interface{} `json:"details,omitempty"`
	Error_ string `json:"error,omitempty"`
	Status *MainStatusCode `json:"status,omitempty"`
}
