/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExtendVolumeResponse struct {
	NeedsRestart bool `json:"needs_restart,omitempty"`
	Volume *Volume `json:"volume,omitempty"`
}
