/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Machine struct {
	Checks []CheckStatus `json:"checks,omitempty"`
	Config *ApiMachineConfig `json:"config,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Events []MachineEvent `json:"events,omitempty"`
	Id string `json:"id,omitempty"`
	ImageRef *ImageRef `json:"image_ref,omitempty"`
	// InstanceID is unique for each version of the machine
	InstanceId string `json:"instance_id,omitempty"`
	Name string `json:"name,omitempty"`
	// Nonce is only every returned on machine creation if a lease_duration was provided.
	Nonce string `json:"nonce,omitempty"`
	// PrivateIP is the internal 6PN address of the machine.
	PrivateIp string `json:"private_ip,omitempty"`
	Region string `json:"region,omitempty"`
	State string `json:"state,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
