/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProcessStat struct {
	Command string `json:"command,omitempty"`
	Cpu int32 `json:"cpu,omitempty"`
	Directory string `json:"directory,omitempty"`
	ListenSockets []ListenSocket `json:"listen_sockets,omitempty"`
	Pid int32 `json:"pid,omitempty"`
	Rss int32 `json:"rss,omitempty"`
	Rtime int32 `json:"rtime,omitempty"`
	Stime int32 `json:"stime,omitempty"`
}
