/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Lease struct {
	// Description or reason for the Lease.
	Description string `json:"description,omitempty"`
	// ExpiresAt is the unix timestamp in UTC to denote when the Lease will no longer be valid.
	ExpiresAt int32 `json:"expires_at,omitempty"`
	// Nonce is the unique ID autogenerated and associated with the Lease.
	Nonce string `json:"nonce,omitempty"`
	// Owner is the user identifier which acquired the Lease.
	Owner string `json:"owner,omitempty"`
}
