/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MachineExecRequest struct {
	// Deprecated: use Command instead
	Cmd string `json:"cmd,omitempty"`
	Command []string `json:"command,omitempty"`
	Timeout int32 `json:"timeout,omitempty"`
}
