/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type App struct {
	Name string `json:"name,omitempty"`
	Organization *Organization `json:"organization,omitempty"`
	Status string `json:"status,omitempty"`
}
