/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateAppRequest struct {
	AppName string `json:"app_name,omitempty"`
	Network string `json:"network,omitempty"`
	OrgSlug string `json:"org_slug,omitempty"`
}
