/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Volume struct {
	AttachedAllocId string `json:"attached_alloc_id,omitempty"`
	AttachedMachineId string `json:"attached_machine_id,omitempty"`
	BlockSize int32 `json:"block_size,omitempty"`
	Blocks int32 `json:"blocks,omitempty"`
	BlocksAvail int32 `json:"blocks_avail,omitempty"`
	BlocksFree int32 `json:"blocks_free,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Encrypted bool `json:"encrypted,omitempty"`
	Fstype string `json:"fstype,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Region string `json:"region,omitempty"`
	SizeGb int32 `json:"size_gb,omitempty"`
	State string `json:"state,omitempty"`
	Zone string `json:"zone,omitempty"`
}
