/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiMachineCheck struct {
	GracePeriod string `json:"grace_period,omitempty"`
	Headers []ApiMachineHttpHeader `json:"headers,omitempty"`
	Interval string `json:"interval,omitempty"`
	Method string `json:"method,omitempty"`
	Path string `json:"path,omitempty"`
	Port int32 `json:"port,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	Timeout string `json:"timeout,omitempty"`
	TlsServerName string `json:"tls_server_name,omitempty"`
	TlsSkipVerify bool `json:"tls_skip_verify,omitempty"`
	Type_ string `json:"type,omitempty"`
}
