/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiMachineMount struct {
	Encrypted bool `json:"encrypted,omitempty"`
	Name string `json:"name,omitempty"`
	Path string `json:"path,omitempty"`
	SizeGb int32 `json:"size_gb,omitempty"`
	Volume string `json:"volume,omitempty"`
}
