/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckStatus struct {
	Name string `json:"name,omitempty"`
	Output string `json:"output,omitempty"`
	Status string `json:"status,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
