/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateVolumeRequest struct {
	Compute *ApiMachineGuest `json:"compute,omitempty"`
	Encrypted bool `json:"encrypted,omitempty"`
	Fstype string `json:"fstype,omitempty"`
	MachinesOnly bool `json:"machines_only,omitempty"`
	Name string `json:"name,omitempty"`
	Region string `json:"region,omitempty"`
	RequireUniqueZone bool `json:"require_unique_zone,omitempty"`
	SizeGb int32 `json:"size_gb,omitempty"`
	// restore from snapshot
	SnapshotId string `json:"snapshot_id,omitempty"`
	// fork from remote volume
	SourceVolumeId string `json:"source_volume_id,omitempty"`
}
