/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiMachineConfig struct {
	AutoDestroy bool `json:"auto_destroy,omitempty"`
	Checks map[string]ApiMachineCheck `json:"checks,omitempty"`
	// Deprecated: use Service.Autostart instead
	DisableMachineAutostart bool `json:"disable_machine_autostart,omitempty"`
	Dns *ApiDnsConfig `json:"dns,omitempty"`
	// Fields managed from fly.toml If you add anything here, ensure appconfig.Config.ToMachine() is updated
	Env map[string]string `json:"env,omitempty"`
	Files []ApiFile `json:"files,omitempty"`
	Guest *ApiMachineGuest `json:"guest,omitempty"`
	HostDedicationId string `json:"host_dedication_id,omitempty"`
	// Set by fly deploy or fly machines commands
	Image string `json:"image,omitempty"`
	Init *ApiMachineInit `json:"init,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	Metrics *ApiMachineMetrics `json:"metrics,omitempty"`
	Mounts []ApiMachineMount `json:"mounts,omitempty"`
	Processes []ApiMachineProcess `json:"processes,omitempty"`
	Restart *ApiMachineRestart `json:"restart,omitempty"`
	// The following fields can only be set or updated by `fly machines run|update` commands \"fly deploy\" must preserve them, if you add anything here, ensure it is propagated on deploys
	Schedule string `json:"schedule,omitempty"`
	Services []ApiMachineService `json:"services,omitempty"`
	// Deprecated: use Guest instead
	Size string `json:"size,omitempty"`
	// Standbys enable a machine to be a standby for another. In the event of a hardware failure, the standby machine will be started.
	Standbys []string `json:"standbys,omitempty"`
	Statics []ApiStatic `json:"statics,omitempty"`
	StopConfig *ApiStopConfig `json:"stop_config,omitempty"`
}
