/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateMachineRequest struct {
	Config *ApiMachineConfig `json:"config,omitempty"`
	CurrentVersion string `json:"current_version,omitempty"`
	LeaseTtl int32 `json:"lease_ttl,omitempty"`
	Lsvd bool `json:"lsvd,omitempty"`
	Name string `json:"name,omitempty"`
	Region string `json:"region,omitempty"`
	SkipLaunch bool `json:"skip_launch,omitempty"`
	SkipServiceRegistration bool `json:"skip_service_registration,omitempty"`
}
