/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiFile struct {
	// GuestPath is the path on the machine where the file will be written and must be an absolute path. i.e. /full/path/to/file.json
	GuestPath string `json:"guest_path,omitempty"`
	// RawValue containts the base64 encoded string of the file contents.
	RawValue string `json:"raw_value,omitempty"`
	// SecretName is the name of the secret that contains the base64 encoded file contents.
	SecretName string `json:"secret_name,omitempty"`
}
