/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiTlsOptions struct {
	Alpn []string `json:"alpn,omitempty"`
	DefaultSelfSigned bool `json:"default_self_signed,omitempty"`
	Versions []string `json:"versions,omitempty"`
}
