/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ImageRef struct {
	Digest string `json:"digest,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	Registry string `json:"registry,omitempty"`
	Repository string `json:"repository,omitempty"`
	Tag string `json:"tag,omitempty"`
}
