/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MainStatusCode string

// List of main.statusCode
const (
	UNKNOWN_MainStatusCode MainStatusCode = "unknown"
	INSUFFICIENT_CAPACITY_MainStatusCode MainStatusCode = "insufficient_capacity"
)
