/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiHttpOptions struct {
	Compress bool `json:"compress,omitempty"`
	Response *ApiHttpResponseOptions `json:"response,omitempty"`
}
