/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiMachineInit struct {
	Cmd []string `json:"cmd,omitempty"`
	Entrypoint []string `json:"entrypoint,omitempty"`
	Exec []string `json:"exec,omitempty"`
	KernelArgs []string `json:"kernel_args,omitempty"`
	SwapSizeMb int32 `json:"swap_size_mb,omitempty"`
	Tty bool `json:"tty,omitempty"`
}
