/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiMachineGuest struct {
	CpuKind string `json:"cpu_kind,omitempty"`
	Cpus int32 `json:"cpus,omitempty"`
	GpuKind string `json:"gpu_kind,omitempty"`
	KernelArgs []string `json:"kernel_args,omitempty"`
	MemoryMb int32 `json:"memory_mb,omitempty"`
}
