/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MachineEvent struct {
	Id string `json:"id,omitempty"`
	Request *interface{} `json:"request,omitempty"`
	Source string `json:"source,omitempty"`
	Status string `json:"status,omitempty"`
	Timestamp int32 `json:"timestamp,omitempty"`
	Type_ string `json:"type,omitempty"`
}
