/*
 * Fly Machines API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListAppsResponse struct {
	Apps []ListApp `json:"apps,omitempty"`
	TotalApps int32 `json:"total_apps,omitempty"`
}
